name: Sync markdown To Notion DB

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    steps:
      - uses: actions/checkout@v3
      - name: Gallery Fake
        uses: litencatt/gallery-fake@v0.2.0
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DATABASE_ID }}
          GITHUB_MD_PATH: "${{ github.workspace }}/service/aaa/specifications"
